version: '3'
services:
  db:
    image: "mysql:8.0"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
  web:
    image: arunvm/twitter-clone:latest
    ports:
      - "8080:8080"